name: Deploy web content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3-pip
          python3 -m pip install meson

      - name: Check tools
        run: |
          which cmake
          which emcc
          echo $PATH

      - name: Configure
        run: meson setup build-wasm --cross-file cross/emscripten.ini

      - name: Build
        run: meson compile -C build-wasm

      - name: Copy build stuff
        run: |
          cp build-wasm/cTetris.js web/
          cp build-wasm/cTetris.wasm web/

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - id: deployment
        uses: actions/deploy-pages@v5
